import { FoodItem, Recipe } from './types';

export const COMMON_FOODS: FoodItem[] = [
  { id: '1', name: 'Cooked White Rice', calories: 130, protein: 2.7, carbs: 28, fats: 0.3 },
  { id: '2', name: 'Cooked Brown Rice', calories: 111, protein: 2.6, carbs: 23, fats: 0.9 },
  { id: '3', name: 'Wheat Roti (1 medium)', calories: 120, protein: 3, carbs: 24, fats: 0.5, servingSize: 40 },
  { id: '4', name: 'Dal (Cooked)', calories: 116, protein: 9, carbs: 20, fats: 0.4 },
  { id: '5', name: 'Paneer', calories: 265, protein: 18, carbs: 1.2, fats: 20 },
  { id: '6', name: 'Chicken Breast (Cooked)', calories: 165, protein: 31, carbs: 0, fats: 3.6 },
  { id: '7', name: 'Egg (Boiled, 1 large)', calories: 155, protein: 13, carbs: 1.1, fats: 11, servingSize: 50 },
  { id: '8', name: 'Idli (1 medium)', calories: 58, protein: 1.6, carbs: 12, fats: 0.1, servingSize: 40 },
  { id: '9', name: 'Dosa (Plain, 1 medium)', calories: 133, protein: 2.1, carbs: 26, fats: 2.4, servingSize: 60 },
  { id: '10', name: 'Sambar', calories: 60, protein: 2.5, carbs: 10, fats: 1.5 },
  { id: '11', name: 'Banana', calories: 89, protein: 1.1, carbs: 23, fats: 0.3 },
  { id: '12', name: 'Apple', calories: 52, protein: 0.3, carbs: 14, fats: 0.2 },
  { id: '13', name: 'Almonds', calories: 579, protein: 21, carbs: 22, fats: 49 },
  { id: '14', name: 'Greek Yogurt', calories: 59, protein: 10, carbs: 3.6, fats: 0.4 },
  { id: '15', name: 'Oats (Cooked)', calories: 68, protein: 2.4, carbs: 12, fats: 1.4 },
  { id: '16', name: 'Spinach (Cooked)', calories: 23, protein: 3, carbs: 3.6, fats: 0.3 },
  { id: '17', name: 'Broccoli (Cooked)', calories: 35, protein: 2.4, carbs: 7, fats: 0.4 },
  { id: '18', name: 'Curd (Indian)', calories: 61, protein: 3.5, carbs: 4.7, fats: 3.3 },
  { id: '19', name: 'Upma', calories: 132, protein: 3, carbs: 25, fats: 2.5 },
  { id: '20', name: 'Poha', calories: 110, protein: 2.3, carbs: 25, fats: 0.2 },
];

export const RECIPES: Recipe[] = [
  {
    id: 'r1',
    name: 'High Protein Paneer Salad',
    description: 'A fresh and healthy salad packed with paneer and veggies.',
    type: 'veg',
    category: 'Lunch',
    ingredients: ['Paneer 100g', 'Cucumber', 'Tomato', 'Onion', 'Lemon juice', 'Salt', 'Pepper'],
    instructions: ['Dice paneer and veggies.', 'Mix in a bowl.', 'Add lemon juice and seasoning.', 'Serve fresh.'],
    calories: 180,
    protein: 15,
    carbs: 8,
    fats: 10,
    servingSize: 250,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r2',
    name: 'Grilled Chicken with Steamed Broccoli',
    description: 'Lean protein meal for muscle gain.',
    type: 'non-veg',
    category: 'Dinner',
    ingredients: ['Chicken Breast 150g', 'Broccoli 100g', 'Olive oil', 'Garlic', 'Herbs'],
    instructions: ['Marinate chicken with garlic and herbs.', 'Grill until cooked.', 'Steam broccoli.', 'Serve together.'],
    calories: 250,
    protein: 35,
    carbs: 5,
    fats: 8,
    servingSize: 300,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r3',
    name: 'Oats Idli',
    description: 'A healthy twist to the traditional idli.',
    type: 'veg',
    category: 'Breakfast',
    ingredients: ['Oats flour', 'Curd', 'Carrots', 'Ginger', 'Chili'],
    instructions: ['Mix oats flour and curd to make batter.', 'Add grated carrots and spices.', 'Steam in idli molds.', 'Serve with chutney.'],
    calories: 120,
    protein: 6,
    carbs: 20,
    fats: 2,
    servingSize: 150,
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r4',
    name: 'Masala Moong Dal',
    description: 'Protein-rich lentil soup.',
    type: 'veg',
    category: 'Lunch',
    ingredients: ['Moong Dal', 'Turmeric', 'Cumin', 'Onion', 'Tomato'],
    instructions: ['Pressure cook dal with turmeric.', 'Sauté onion and tomato with cumin.', 'Mix dal and sautéed veggies.', 'Garnish with coriander.'],
    calories: 150,
    protein: 10,
    carbs: 22,
    fats: 3,
    servingSize: 200,
    imageUrl: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r5',
    name: 'Healthy Chicken Biryani',
    description: 'A low-oil, high-protein version of the classic biryani using brown rice.',
    type: 'non-veg',
    category: 'Dinner',
    ingredients: ['Chicken 200g', 'Brown Rice 1 cup', 'Yogurt', 'Biryani Spices', 'Mint', 'Coriander'],
    instructions: ['Marinate chicken in yogurt and spices for 1 hour.', 'Cook brown rice until 70% done.', 'Layer chicken and rice in a pot.', 'Cook on low heat (dum) for 20 mins.'],
    calories: 350,
    protein: 28,
    carbs: 45,
    fats: 8,
    servingSize: 400,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r6',
    name: 'Sprouts & Pomegranate Salad',
    description: 'A crunchy, nutrient-dense salad perfect for a mid-day snack.',
    type: 'veg',
    category: 'Snack',
    ingredients: ['Moong Sprouts', 'Pomegranate seeds', 'Roasted Peanuts', 'Lemon', 'Chaat Masala'],
    instructions: ['Steam sprouts slightly.', 'Mix with pomegranate and peanuts.', 'Add lemon juice and chaat masala.', 'Toss well and serve.'],
    calories: 110,
    protein: 7,
    carbs: 18,
    fats: 2,
    servingSize: 150,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r7',
    name: 'Fish Curry (South Indian Style)',
    description: 'Tangy and spicy fish curry made with minimal oil and coconut milk.',
    type: 'non-veg',
    category: 'Lunch',
    ingredients: ['Fish Fillets 200g', 'Tamarind paste', 'Coconut milk', 'Curry leaves', 'Mustard seeds'],
    instructions: ['Sauté mustard seeds and curry leaves.', 'Add tamarind paste and water.', 'Simmer with fish fillets until cooked.', 'Stir in coconut milk and serve.'],
    calories: 220,
    protein: 24,
    carbs: 6,
    fats: 12,
    servingSize: 300,
    imageUrl: 'https://images.unsplash.com/photo-1621510456681-23a23cfb5f57?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r8',
    name: 'Paneer Power Bowl',
    description: 'A high-protein vegetarian bowl with fresh paneer and veggies.',
    type: 'veg',
    category: 'Lunch',
    ingredients: ['Paneer – 150g', 'Cucumber – 50g', 'Tomato – 50g', 'Onion – 30g', 'Lemon juice – 10g', 'Salt – 2g', 'Pepper – 2g'],
    instructions: ['Dice paneer and vegetables.', 'Add all to a bowl.', 'Add lemon juice and seasoning.', 'Mix and serve fresh.'],
    calories: 320,
    protein: 22,
    carbs: 12,
    fats: 22,
    servingSize: 300,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r9',
    name: 'Soya Chunk Stir Fry',
    description: 'Quick and easy protein-packed soya stir fry.',
    type: 'veg',
    category: 'Dinner',
    ingredients: ['Soya chunks – 50g', 'Onion – 50g', 'Capsicum – 50g', 'Oil – 5g', 'Soy sauce – 5g', 'Salt – 2g'],
    instructions: ['Boil soya chunks and squeeze water.', 'Heat oil and sauté onion.', 'Add capsicum and soya chunks.', 'Add soy sauce, salt and cook.'],
    calories: 300,
    protein: 26,
    carbs: 20,
    fats: 10,
    servingSize: 200,
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r10',
    name: 'Moong Dal Protein Chilla',
    description: 'Nutritious lentil pancakes for a healthy start.',
    type: 'veg',
    category: 'Breakfast',
    ingredients: ['Moong dal – 120g', 'Onion – 30g', 'Green chilli – 5g', 'Salt – 2g', 'Oil – 5g'],
    instructions: ['Grind soaked dal.', 'Add onion, chilli and salt.', 'Spread batter on pan.', 'Cook both sides and serve.'],
    calories: 260,
    protein: 18,
    carbs: 28,
    fats: 6,
    servingSize: 180,
    imageUrl: 'https://images.unsplash.com/photo-1624462966581-bc6d768cbce5?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r11',
    name: 'Greek Yogurt Protein Bowl',
    description: 'Creamy yogurt topped with nuts and seeds.',
    type: 'veg',
    category: 'Breakfast',
    ingredients: ['Greek yogurt – 200g', 'Almonds – 15g', 'Chia seeds – 10g', 'Honey – 5g'],
    instructions: ['Add yogurt to bowl.', 'Add almonds and chia seeds.', 'Drizzle honey.', 'Mix and serve.'],
    calories: 220,
    protein: 20,
    carbs: 10,
    fats: 8,
    servingSize: 240,
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r12',
    name: 'Paneer Scramble',
    description: 'Spiced crumbled paneer with tomatoes and onions.',
    type: 'veg',
    category: 'Breakfast',
    ingredients: ['Paneer – 150g', 'Onion – 50g', 'Tomato – 50g', 'Oil – 5g', 'Salt – 2g'],
    instructions: ['Heat oil and sauté onion.', 'Add tomato and cook.', 'Crumble paneer and mix.', 'Cook briefly and serve.'],
    calories: 310,
    protein: 21,
    carbs: 8,
    fats: 24,
    servingSize: 250,
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r13',
    name: 'Grilled Chicken Bowl',
    description: 'Classic grilled chicken breast with simple seasoning.',
    type: 'non-veg',
    category: 'Lunch',
    ingredients: ['Chicken breast – 150g', 'Olive oil – 5g', 'Garlic – 5g', 'Salt – 2g', 'Pepper – 2g'],
    instructions: ['Marinate chicken with spices.', 'Heat pan and add oil.', 'Grill chicken until cooked.', 'Slice and serve.'],
    calories: 350,
    protein: 35,
    carbs: 10,
    fats: 18,
    servingSize: 160,
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r14',
    name: 'Egg White Omelette',
    description: 'Light and high-protein omelette with veggies.',
    type: 'non-veg',
    category: 'Breakfast',
    ingredients: ['Egg whites – 5 (150g)', 'Onion – 30g', 'Capsicum – 30g', 'Oil – 5g', 'Salt – 2g'],
    instructions: ['Beat egg whites.', 'Add chopped vegetables.', 'Pour into pan with oil.', 'Cook and fold.'],
    calories: 200,
    protein: 22,
    carbs: 5,
    fats: 6,
    servingSize: 200,
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r15',
    name: 'Chicken Stir Fry',
    description: 'Savory chicken strips sautéed with crisp vegetables.',
    type: 'non-veg',
    category: 'Dinner',
    ingredients: ['Chicken breast – 150g', 'Onion – 50g', 'Capsicum – 50g', 'Oil – 5g', 'Soy sauce – 5g'],
    instructions: ['Heat oil in pan.', 'Add chicken and cook.', 'Add vegetables.', 'Add soy sauce and stir fry.'],
    calories: 330,
    protein: 32,
    carbs: 12,
    fats: 15,
    servingSize: 260,
    imageUrl: 'https://images.unsplash.com/photo-1603133872878-685f548e7a1a?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r16',
    name: 'Boiled Egg Salad',
    description: 'Simple and filling egg salad with fresh veggies.',
    type: 'non-veg',
    category: 'Snack',
    ingredients: ['Boiled eggs – 3 (150g)', 'Cucumber – 50g', 'Tomato – 50g', 'Salt – 2g', 'Pepper – 2g'],
    instructions: ['Chop boiled eggs and vegetables.', 'Add to bowl.', 'Season with salt and pepper.', 'Mix and serve.'],
    calories: 280,
    protein: 20,
    carbs: 6,
    fats: 20,
    servingSize: 250,
    imageUrl: 'https://images.unsplash.com/photo-1522747776116-64ee0d049c6f?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'r17',
    name: 'Tuna Protein Salad',
    description: 'Zesty tuna salad with lemon and olive oil.',
    type: 'non-veg',
    category: 'Lunch',
    ingredients: ['Tuna – 120g', 'Onion – 30g', 'Lemon juice – 10g', 'Olive oil – 5g', 'Salt – 2g'],
    instructions: ['Add tuna to bowl.', 'Add chopped onion.', 'Add lemon juice and oil.', 'Mix and serve.'],
    calories: 300,
    protein: 30,
    carbs: 5,
    fats: 15,
    servingSize: 160,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop'
  }
];
